### ISSUE TITLE
Help with extracting EEG signal matched to the audio stimulus duration

### ISSUE THREAD

**Issue by neerajww** [mabhijithn/eeg-analyse#2]
Hi,

I tried using the trigger signal channel to extract the EEG corresponding to the audio stimulus.  But I find that the duration of extracted EEG and the audio stimulus don't match. Can you please help with this crucial step. It will benefit analysing this (https://zenodo.org/record/4518754#.YfmM6vXTXqt) very interesting dataset. Also, thank you for sharing the dataset. 
Below is an example of my code snippet to extract the "audio stimulus attended"-EEG signal. 

```    
        # load curry file into mne object
        raw = mne.io.read_raw_curry(path_data_eeg + 'S' + str(sub_id) + '/S' + str(sub_id) + '_AAD_' + expt_type + '.dat')
        # get eeg data
        data = raw.get_data()
        # Trigger channel index is 255
        # Get trigger instants
        indx = np.where(np.diff(data[255,:])>0)[0]
        # get first and last trigger instant
        indx = [indx[0], indx[-1]]
        # eeg duration
        print((indx[1] - indx[0])/fs_eeg/60, ' mins')
```

**Comment by mabhijithn** [comment]
Yes. The stimuli files and EEG data are not exactly the same duration. The start of the stimuli and EEG are aligned by triggers. For the end of data, the EEG data's end-trigger can be used and not the stimuli duration. The analysis reported in the paper were carried out so.

**Comment by neerajww** [comment]
This helps. Thank you for the quick reply. Can you also clarify the following.
In the Zenodo page (https://zenodo.org/record/4518754#.YfmM6vXTXqt) it is stated that - quoting below

--
1. Trial n of subject x attending to left-ear has the name: Sx_AAD_nL.
2. Trial n of subject x attending to right-ear has the name: Sx_AAD_nR.
--
But in the dataset n is {1,2} and not {1, 2, 3, 4}. Can you help understand how the above maps to the below - again quoting from Zenodo page ..
--
Trial (n)      Left-ear                   Right-ear
1                part1_track1_dry     part1_track2_dry
2                part1_track1_dry     part1_track2_dry
3                part2_track2_dry     part2_track1_dry
4                part2_track2_dry     part2_track1_dry
--

**Comment by mabhijithn** [comment]
This is indeed confusing and incorrect. The database has been updated with the correct info. Please check the page.
In summary: 
Trial      Left-ear stimuli        Right-ear  stimuli
1L         part1_track1_dry     part1_track2_dry


1R         part1_track1_dry     part1_track2_dry


2L         part2_track2_dry     part2_track1_dry


2R         part2_track2_dry     part2_track1_dry

**Comment by neerajww** [comment]
Thank you! 🙏
